//
//  GraphChatIntentInterpretation.swift
//  BrainMesh
//
//  Value-only, turn-bound interpretation of an app-validated graph-chat intent.
//

import Foundation

nonisolated enum GraphChatIntentInterpretationVersion:
    Int,
    CaseIterable,
    Hashable,
    Sendable
{
    case v1 = 1
}

nonisolated struct GraphChatIntentInterpretationScopeBinding:
    Hashable,
    Sendable
{
    let graphScope: GraphScope
    let chatScope: GraphChatScope
    let queryScope: GraphChatScope
}

nonisolated struct GraphChatIntentInterpretationTurnBinding:
    Hashable,
    Sendable
{
    let requestID: UUID
    let conversationID: UUID
    let turnID: UUID
    let sourceTurnID: UUID?
}

nonisolated struct GraphChatIntentInterpretationEntity:
    Hashable,
    Sendable
{
    let id: UUID
    let displayName: String

    init(_ identity: GraphChatTypedEntityIdentity) {
        id = identity.id
        displayName = identity.displayName
    }

    init(
        id: UUID,
        displayName: String
    ) {
        self.id = id
        self.displayName = displayName
    }
}

nonisolated struct GraphChatIntentInterpretationNode:
    Hashable,
    Sendable
{
    let node: NodeRefKey
    let ownerEntityID: UUID
    let displayName: String

    init(_ identity: GraphChatTypedNodeIdentity) {
        node = identity.node
        ownerEntityID = identity.ownerEntityID
        displayName = identity.displayName
    }

    init(
        node: NodeRefKey,
        ownerEntityID: UUID,
        displayName: String
    ) {
        self.node = node
        self.ownerEntityID = ownerEntityID
        self.displayName = displayName
    }
}

nonisolated struct GraphChatIntentInterpretationField:
    Hashable,
    Sendable
{
    let id: UUID
    let ownerEntityID: UUID
    let displayName: String
    let type: DetailFieldType
    let unit: String?

    init(_ identity: GraphChatTypedFieldIdentity) {
        id = identity.id
        ownerEntityID = identity.ownerEntityID
        displayName = identity.displayName
        type = identity.type
        unit = identity.unit
    }

    init(
        id: UUID,
        ownerEntityID: UUID,
        displayName: String,
        type: DetailFieldType,
        unit: String?
    ) {
        self.id = id
        self.ownerEntityID = ownerEntityID
        self.displayName = displayName
        self.type = type
        self.unit = unit
    }
}

nonisolated struct GraphChatIntentInterpretationFilter:
    Hashable,
    Sendable
{
    let field: GraphChatIntentInterpretationField
    let operation: GraphQueryFilterOperator
    let value: GraphValidatedFilterValue
}

nonisolated enum GraphChatIntentInterpretationSortKey:
    Hashable,
    Sendable
{
    case nodeName
    case field(GraphChatIntentInterpretationField)
}

nonisolated struct GraphChatIntentInterpretationSort:
    Hashable,
    Sendable
{
    let key: GraphChatIntentInterpretationSortKey
    let direction: GraphQuerySortDirection
}

nonisolated struct GraphChatIntentInterpretationGrouping:
    Hashable,
    Sendable
{
    let field: GraphChatIntentInterpretationField
}

nonisolated enum GraphChatIntentInterpretationAggregation:
    Hashable,
    Sendable
{
    case count
    case groupCount(GraphChatIntentInterpretationField)
}

nonisolated enum GraphChatIntentInterpretationResultExtentKind:
    String,
    CaseIterable,
    Hashable,
    Sendable
{
    case singleResult
    case boundedCollection
    case completeAuthorizedCollection
    case refinedCollection
    case comparison
    case graphState
}

nonisolated struct GraphChatIntentInterpretationResultExtent:
    Hashable,
    Sendable
{
    let kind: GraphChatIntentInterpretationResultExtentKind
    let expectedCardinality: GraphChatTypedIntentExpectedCardinality
    let resultLimit: Int
    let maximumResultLimit: Int
    let subjectCount: Int?
    let includesAllAuthorizedResults: Bool
}

nonisolated enum GraphChatIntentInterpretationEditableComponent:
    String,
    CaseIterable,
    Hashable,
    Sendable
{
    case entity
    case nodes
    case fields
    case filters
    case sorting
    case grouping
    case aggregation
    case resultExtent
    case sourceResultSet
    case graphStateAspect
}

nonisolated struct GraphChatIntentInterpretationPresentation:
    Hashable,
    Sendable
{
    let label: String
    let title: String

    var accessibilityLabel: String {
        "\(label): \(title)"
    }
}

/// App-owned interpretation data. Technical identities are retained only for
/// binding and revalidation. Visible text is generated by
/// `GraphChatIntentInterpretationRenderer`.
nonisolated struct GraphChatIntentInterpretation:
    Hashable,
    Sendable
{
    let version: GraphChatIntentInterpretationVersion
    let intentKind: GraphChatTypedIntentKind
    let scopeBinding: GraphChatIntentInterpretationScopeBinding
    let turnBinding: GraphChatIntentInterpretationTurnBinding
    let responseLanguage: GraphChatResponseLanguage
    let entities: [GraphChatIntentInterpretationEntity]
    let nodes: [GraphChatIntentInterpretationNode]
    let fields: [GraphChatIntentInterpretationField]
    let projectedFields: [GraphChatIntentInterpretationField]
    let filters: [GraphChatIntentInterpretationFilter]
    let sorting: [GraphChatIntentInterpretationSort]
    let grouping: GraphChatIntentInterpretationGrouping?
    let aggregation: GraphChatIntentInterpretationAggregation?
    let resultExtent: GraphChatIntentInterpretationResultExtent
    let graphStateAspect: GraphChatGraphStateAspect?
    let resolutionSource: GraphChatTypedIntentResolutionSource
    let resolutionOrigin: GraphChatTypedIntentResolutionOrigin
    let resolutionQuality: GraphChatTypedIntentResolutionQuality
    let editableComponents:
        [GraphChatIntentInterpretationEditableComponent]
    let formattingTimeZoneIdentifier: String
    let correctionOrigin:
        GraphChatInterpretationCorrectionOrigin?

    var presentation: GraphChatIntentInterpretationPresentation {
        GraphChatIntentInterpretationRenderer()
            .presentation(for: self)
    }

    var isInternallyConsistent: Bool {
        guard version == .v1,
              scopeBinding.graphScope
                == scopeBinding.chatScope.graphScope,
              scopeBinding.graphScope
                == scopeBinding.queryScope.graphScope,
              turnBinding.requestID
                == turnBinding.turnID,
              resultExtent.resultLimit > 0,
              resultExtent.maximumResultLimit > 0,
              resultExtent.resultLimit
                <= resultExtent.maximumResultLimit,
              resultExtent.subjectCount
                .map({ $0 > 0 }) ?? true,
              TimeZone(
                  identifier:
                      formattingTimeZoneIdentifier
              ) != nil,
              Set(entities.map(\.id)).count
                == entities.count,
              Set(nodes.map(\.node)).count
                == nodes.count,
              Set(fields.map(\.id)).count
                == fields.count,
              Set(projectedFields.map(\.id)).count
                == projectedFields.count,
              Set(editableComponents).count
                == editableComponents.count
        else {
            return false
        }

        let entityIDs = Set(entities.map(\.id))
        guard nodes.allSatisfy({
            entityIDs.contains($0.ownerEntityID)
        }),
        fields.allSatisfy({
            entityIDs.contains($0.ownerEntityID)
        }),
        projectedFields.allSatisfy({
            fields.contains($0)
        }),
        filters.allSatisfy({
            fields.contains($0.field)
        }),
        sorting.allSatisfy({ sort in
            if case .field(let field) = sort.key {
                return fields.contains(field)
            }
            return true
        }) else {
            return false
        }

        if let grouping,
           fields.contains(grouping.field) == false {
            return false
        }
        if let aggregation {
            if case .groupCount(let field) = aggregation,
               fields.contains(field) == false {
                return false
            }
        }
        if intentKind == .inspectGraphState {
            guard graphStateAspect != nil else {
                return false
            }
        } else if graphStateAspect != nil {
            return false
        }
        if let correctionOrigin {
            return correctionOrigin.matches(self)
        }
        return true
    }

    var isCorrectionEditable: Bool {
        correctionOrigin?.matches(self) == true
            && editableComponents.isEmpty == false
    }
}
